aws:
  region: us-east-1
  table_name: HealthCareCases
  s3_bucket: demohealthcarecasemanagement

app:
  page_title: "Healthcare Case Manager"
  page_icon: "ğŸ¥"
  layout: "wide"

ui:
  refresh_interval: 30  # seconds
  max_cases_display: 1000